#! /bin/sh
# 设置shell命令的搜索路径
PATH=/sbin:/bin:/usr/sbin:/usr/bin
# 运行模式为: 单用户模式
runlevel=S
# 前一个级别，为N则表示没有前一个级别
prevlevel=N
# 默认的权限位掩码, 创建文件/目录时会用到
umask 022
# 导出为环境变量
export PATH runlevel prevlevel
# 配置eth0的IP地址(这里不建议配置IP, 硬编码配置IP会导致其他网络环境无法挂载NFS文件系统)
# ifconfig eth0 XX.XX.XX.XX
# 文件/etc/fstab 中指明的文件挂载到对应的挂载点上
mount -a
# 当有热插拔事件产生时， 内核就会调用位于/sbin目录的mdev; 利用相关信息创建设备节点;
echo /sbin/mdev > /proc/sys/kernel/hotplug
# 建立dev目录;以'-s'为参数调用位于/sbin 目录写的 mdev
# mdev扫描 /sys/class和/sys/block中所有的类设备目录，如果在目录中含有名为"dev"的文件，
# 且文件中包含的是设备号，则 mdev 就利用这些信息为这个设备在/dev下创建设备节点文件。
# 一般只在启动时才执行一次  "mdev -s"
mdev -s
